version: '2'


services:
  zipkin:
    image: 11.4.76.193/redis/zipkin:2.8.4
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_INDEX=zipkin
      - KAFKA_TOPIC=zipkin
      - ES_HOSTS=11.4.74.45:19200,11.4.74.50:19200,11.4.74.47:19200
   
      - KAFKA_BOOTSTRAP_SERVERS=10.42.66.168:9092,10.42.220.122:9092,10.42.150.222:9092


  lb:
    image: 11.4.76.186/rancher/lb-service-haproxy:v0.7.15
    ports:
    - 9411:9411/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'


