
version: '2'

volumes:
  rbd:
    driver: rancher-rbd
    per_container: true
    driver_opts:
      pool: rbd
      size: 30G
services:
  namesrv1:
    image: 11.4.76.193/redis/rocketmq-namesrv:4.3
    network_mode: host
    volumes:
      - rbd:/rocketmq/store
      - rbd:/rocketmq/logs
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: app_label_to_host=namesrv_cluster_06645
      app_label_to_host: namesrv_cluster_06645
  namesrv2:
    image: 11.4.76.193/redis/rocketmq-namesrv:4.3
    network_mode: host
    volumes:
      - rbd:/rocketmq/store
      - rbd:/rocketmq/logs
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: app_label_to_host=namesrv_cluster_06645
      app_label_to_host: namesrv_cluster_06645
 
  broker-a:
    image: 11.4.76.193/redis/rocketmq-broker:4.3
    network_mode: host
    volumes:
      - rbd:/rocketmq/store
      - rbd:/rocketmq/logs
    environment:
      MEMORY: "-Xms4G -Xmx4G -Xmn2G"
    command: "sh bin/mqbroker -c ./conf/2m-2s-async/broker-a.properties -n namesrv1:9876;namesrv2:9876"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: app_label_to_host=broker_06645
      app_label_to_host: broker_06645
      io.rancher.container.dns: 'true'


  broker-a-s:
    image: 11.4.76.193/redis/rocketmq-broker:4.3
    network_mode: host
    stdin_open: true 
    tty: true   
    environment:
      MEMORY: "-Xms4G -Xmx4G -Xmn2G"
    volumes:
      - rbd:/rocketmq/store
      - rbd:/rocketmq/logs
    command: "sh bin/mqbroker -c ./conf/2m-2s-async/broker-a-s.properties -n namesrv1:9876;namesrv2:9876"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: app_label_to_host=broker_06645
      app_label_to_host: broker_06645
      io.rancher.container.dns: 'true'

  broker-b:
    image: 11.4.76.193/redis/rocketmq-broker:4.3
    network_mode: host
    stdin_open: true 
    tty: true   
    environment:
      MEMORY: "-Xms4G -Xmx4G -Xmn2G"
    volumes:
      - rbd:/rocketmq/store
      - rbd:/rocketmq/logs
    command: "sh bin/mqbroker -c ./conf/2m-2s-async/broker-b.properties -n namesrv1:9876;namesrv2:9876"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: app_label_to_host=broker_06645
      app_label_to_host: broker_06645
      io.rancher.container.dns: 'true'

  broker-b-s:
    image: 11.4.76.193/redis/rocketmq-broker:4.3
    network_mode: host
    stdin_open: true 
    tty: true   
    environment:
      MEMORY: "-Xms4G -Xmx4G -Xmn2G"
    volumes:
      - rbd:/rocketmq/store
      - rbd:/rocketmq/logs
    command: "sh bin/mqbroker -c ./conf/2m-2s-async/broker-b-s.properties -n namesrv1:9876;namesrv2:9876"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: app_label_to_host=broker_06645
      app_label_to_host: broker_06645
      io.rancher.container.dns: 'true'
