version: '2'
services:
  namesrv1:
    retain_ip: true
    scale: 1
    start_on_create: true
  namesrv2:
    retain_ip: true
    scale: 1
    start_on_create: true

  broker-a:
    retain_ip: true
    scale: 1
    start_on_create: true
  broker-a-s:
    retain_ip: true
    scale: 1
    start_on_create: true
  broker-b:
    retain_ip: true
    scale: 1
    start_on_create: true
  broker-b-s:
    retain_ip: true
    scale: 1
    start_on_create: true
  broker-c:
    retain_ip: true
    scale: 1
    start_on_create: true
  broker-c-s:
    retain_ip: true
    scale: 1
    start_on_create: true



