version: '2'

volumes:
  rbd:
    driver: rancher-rbd
    per_container: true
    driver_opts:
      pool: rbd
      size: 30G
services:
  redis-node:
    image: 11.4.76.193/redis/redis:4.0
    volumes:
       - rbd:/redis/data
    privileged: true
    sysctls:
      net.core.somaxconn: 16384
      vm.max_map_count: 655360
      vm.overcommit_memory: 1
      vm.swappiness: 0
      vm.min_free_kbytes: 5000
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: app_label_to_host=redis_cluster_066451
      app_label_to_host: redis_cluster_066451

