version: '2'
services:
  redis-node:
    retain_ip: true
    scale: 6
    start_on_create: true
    health_check:
          response_timeout: 2000
          healthy_threshold: 2
          port: 6000
          unhealthy_threshold: 3
          initializing_timeout: 60000
          interval: 2000
          strategy: recreate
          reinitializing_timeout: 60000
 